# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

# Osiris config

isisdir: 	 /path/to/your/isis/bin/xml
isistoc: 	 applicationTOC.xml
isiscats: 	 applicationCategories.xml
workingdir:      /where/the/user/files/are
extrafields: 	 /home/mike/Isis/extras/extra.xml
